<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JFIIDIB" name="tests.TestLoginBank" tests="9" failures="1" timestamp="7 Aug 2020 01:19:40 GMT" time="61.036" errors="0">
  <testcase name="verifyAcessInvalid" time="5.905" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessInvalid" time="4.167" classname="tests.TestLoginBank">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy11.getAttribute(Unknown Source)
	at page_objects.LogInBankPage.verifyErrorLogin(LogInBankPage.java:68)
	at tests.TestLoginBank.verifyAcessInvalid(TestLoginBank.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyAcessInvalid -->
  <testcase name="verifyAcessInvalid" time="6.942" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessSuccessfully" time="6.981" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessSuccessfully" time="6.112" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessEmpty" time="6.634" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessEmpty" time="5.819" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessEmpty" time="9.527" classname="tests.TestLoginBank"/>
  <testcase name="verifyAcessSuccessfully" time="8.949" classname="tests.TestLoginBank"/>
</testsuite> <!-- tests.TestLoginBank -->
